trigger:
  branches:
    include:
      - refs/tags/release-v*

pr: none

pool:
  vmImage: 'macOS-13'

variables:
  - group: nuget.org

steps:

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Tonestro.Droid.Kotlin.Parcelize.Runtime/Tonestro.Droid.Kotlin.Parcelize.Runtime.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

- bash: |
    echo "##vso[build.updatebuildnumber]production-tonestro-droid-kotlin-parcelize-runtime-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    msbuild /t:Restore
  displayName: Restore Solution

- bash: |
    cd Tonestro.Droid.Kotlin.Android.Extensions.Runtime
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Tonestro.Droid.Kotlin.Android.Extensions.Runtime: Build Release Nuget"

- bash: |
    cd Tonestro.Droid.Kotlin.Parcelize.Runtime
    msbuild /t:Restore /p:Configuration=Release
    msbuild /t:Build /p:Configuration=Release
    msbuild /t:Pack /p:Configuration=Release
  displayName: "Tonestro.Droid.Kotlin.Parcelize.Runtime: Build Release Nuget"

- bash: |
    ./copy-nugets.sh
  displayName: "Copy nugets to nugetoutput folder"

- bash: |
    dotnet nuget push nugetoutput/Tonestro.Droid.Kotlin.Android.Extensions.Runtime.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Tonestro.Droid.Kotlin.Parcelize.Runtime.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
  displayName: "Publish nuget packages to nuget.org"

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Tonestro.Droid.Kotlin.Parcelize.Runtime'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Tonestro.Droid.Kotlin.Parcelize.Runtime $(bindingsVersion)'
    assets: 'nugetoutput/Tonestro.Droid.Kotlin.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
